document.write("<table width=\"930\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
document.write("	<tr height=\"15\">");
document.write("		<td width=\"15\" rowspan=\"3\" background=\"1_border_left.jpg\"></td>");
document.write("		<td width=\"190\"bgcolor=\"#B1C3D9\"></td>");
document.write("		<td width=\"690\" bgcolor=\"#FFFFEE\"></td>");
document.write("		<td width=\"20\" bgcolor=\"#E3E9F1\"></td>");
document.write("		<td width=\"15\" rowspan=\"3\" background=\"2_border_right.jpg\"></td>");
document.write("	</tr>");
document.write("	<tr height=\"4\">");
document.write("		<td colspan=\"3\" bgcolor=\"#F0C030\"></td>");
document.write("	</tr>");
document.write("	<tr height=\"1\">");
document.write("		<td colspan=\"3\" bgcolor=\"#000030\"></td>");
document.write("	</tr>");
document.write("</table>");

document.write("<table width=\"930\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
document.write("	<tr height=\"130\">");
document.write("		<td width=\"15\" background=\"2_border_left.jpg\"></td>");
document.write("		<td width=\"30\" bgcolor=\"#243A74\"></td>");
document.write("		<td width=\"130\" bgcolor=\"#243A74\"><a href=\"http://dragonstar.ict.ac.cn\" target=\"_blank\"><img src=\"3_logo_star.gif\" border=\"0\"></a></td>");
document.write("		<td width=\"30\" bgcolor=\"#243A74\"></td>");
document.write("		<td width=\"540\" background=\"4_head_bg.jpg\"><img src=\"5_head_new.png\" border=\"0\"></td>");
document.write("		<td width=\"20\" background=\"5_head_bg.jpg\"></td>");
document.write("		<td width=\"130\" background=\"5_head_bg.jpg\"><a href=\"http://www.hnu.edu.cn\" target=\"_blank\"><img src=\"6_logo_sjtu.gif\" border=\"0\"></a></td>");
document.write("		<td width=\"20\" bgcolor=\"#243A74\"></td>");
document.write("		<td width=\"15\" background=\"6_border_right.jpg\"></td>");
document.write("	</tr>");
document.write("</table>");

document.write("<table width=\"930\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\">");
document.write("	<tr height=\"1\">");
document.write("		<td width=\"15\" rowspan=\"2\" background=\"6_border_left.jpg\"></td>");
document.write("		<td width=\"900\" bgcolor=\"#000030\"></td>");
document.write("		<td width=\"15\" rowspan=\"2\" background=\"6_border_right.jpg\"></td>");
document.write("	</tr>");
document.write("	<tr height=\"2\">");
document.write("		<td bgcolor=\"#9090A0\"></td>");
document.write("	</tr>");
document.write("</table>");
