document.write("		<td valign=\"top\">");
document.write("			<table width=\"150\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" align=\"center\">");
document.write("				<tbody><tr height=\"10\">");
document.write("					<td></td>");
document.write("				</tr>");
document.write("				<tr height=\"1\">");
document.write("					<td bgcolor=\"#D0D0D0\"></td>");
document.write("				</tr>");
document.write("				<tr height=\"35\" valign=\"middle\">");
document.write("					<td align=\"center\"><a href=\"./index.html\" class=\"menu\">最&nbsp;新&nbsp;消&nbsp;息</a></td>");
document.write("				</tr>");
document.write("				<tr height=\"1\">");
document.write("					<td bgcolor=\"#D0D0D0\"></td>");
document.write("				</tr>");
document.write("				<tr height=\"35\" valign=\"middle\">");
document.write("					<td align=\"center\"><a href=\"./introduction.html\" class=\"menu\">课&nbsp;程&nbsp;简&nbsp;介</a></td>");
document.write("				</tr>");
document.write("				<tr height=\"1\">");
document.write("					<td bgcolor=\"#D0D0D0\"></td>");
document.write("				</tr>");
document.write("				<tr height=\"35\" valign=\"middle\">");
document.write("					<td align=\"center\"><a href=\"./teacher.html\" class=\"menu\">教&nbsp;师&nbsp;信&nbsp;息</a></td>");
document.write("				</tr>");
document.write("				<tr height=\"1\">");
document.write("					<td bgcolor=\"#D0D0D0\"></td>");
document.write("				</tr>");
document.write("				<tr height=\"35\" valign=\"middle\">");
document.write("					<td align=\"center\"><a href=\"./context.html\" class=\"menu\">课&nbsp;程&nbsp;内&nbsp;容</a></td>");
document.write("				</tr>");
document.write("				<tr height=\"1\">");
document.write("					<td bgcolor=\"#D0D0D0\"></td>");
document.write("				</tr>");
document.write("				<tr height=\"35\" valign=\"middle\">");
document.write("					<td align=\"center\"><a href=\"./resources.html\" class=\"menu\">课&nbsp;件&nbsp;下&nbsp;载</a></td>");
document.write("				</tr>");
document.write("				<tr height=\"1\">");
document.write("					<td bgcolor=\"#D0D0D0\"></td>");
document.write("				</tr>");
document.write("				<tr height=\"35\" valign=\"middle\">");
document.write("					<td align=\"center\"><a href=\"./hotel.html\" class=\"menu\">住&nbsp;宿&nbsp;信&nbsp;息</a></td>");
document.write("				</tr>");
document.write("				<tr height=\"1\">");
document.write("					<td bgcolor=\"#D0D0D0\"></td>");
document.write("				</tr>");
document.write("				<tr height=\"35\" valign=\"middle\">");
document.write("					<td align=\"center\"><a href=\"./traffic.html\" class=\"menu\">交&nbsp;通&nbsp;信&nbsp;息</a></td>");
document.write("				</tr>");
document.write("				<tr height=\"1\">");
document.write("					<td bgcolor=\"#D0D0D0\"></td>");
document.write("				</tr>");
document.write("				<tr height=\"35\" valign=\"middle\">");
document.write("					<td align=\"center\"><a href=\"./apply.html\" class=\"menu\">报&nbsp;名&nbsp;联&nbsp;系</a></td>");
document.write("				</tr>");
document.write("				<tr height=\"1\">");
document.write("					<td bgcolor=\"#D0D0D0\"></td>");
document.write("				</tr>");

document.write("			</tbody></table>");
document.write("		</td>");
document.write("");
