document.write("<table width=\"930\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" bgcolor=\"#FFFFFF\">");
document.write("	<tr height=\"3\">");
document.write("		<td width=\"15\" rowspan=\"4\" background=\"0_border_left.jpg\"></td>");
document.write("		<td width=\"900\" colspan=\"5\" bgcolor=\"#DDDDFF\"></td>");
document.write("		<td width=\"15\" rowspan=\"4\" background=\"0_border_right.jpg\"></td>");
document.write("	</tr>");
document.write("	<tr height=\"5\">");
document.write("		<td colspan=\"5\"></td>");
document.write("	</tr>");
document.write("	<tr height=\"25\">");
document.write("		<td width=\"20\"></td>");
document.write("		<td width=\"300\" align=\"left\" class=\"foot\">版权所有&copy;&nbsp;2015&nbsp;&nbsp;<a href='http://www.hnu.edu.cn' class='footlink' target='_black'>湖南大学</a></td>");
document.write("		<td width=\"400\" align=\"center\" class=\"foot\"></td>");
document.write("		<td width=\"200\" align=\"right\" class=\"foot\"><a href='http://www.se.sjtu.edu.cn' class='footlink' target='_black'></a></td>");
document.write("		<td width=\"20\"></td>");
document.write("	</tr>");
document.write("	<tr height=\"5\">");
document.write("		<td colspan=\"5\"></td>");
document.write("	</tr>");
document.write("	<tr height=\"15\">");
document.write("		<td background=\"1_border_left_bottom.jpg\"></td>");
document.write("		<td colspan=\"5\" background=\"2_border_bottom.jpg\"></td>");
document.write("		<td background=\"3_border_right_bottom.jpg\"></td>");
document.write("	</tr>");
document.write("</table>");
